env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - functional
rules:
  functional/functional-parameters: 0
  functional/no-expression-statement: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
